    {
        "nom_magasin": "carfour",
        "adresse": "Adresse, 1400 France",
        "telephone": "123-456-7890",
        "numero": "1234759",
        "caissiere": "nathi Lune",
        "datas": [
            {
                "nomArticle": "livre",
                "autreModele": "",
                "noticeDoc": "http://poc.billib.fr/assets/doc/fr_V3.pdf",
                "notice": "http://poc.billib.fr/assets/doc/fr_V3.pdf",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 100.00
            },
            {
                "nomArticle": "Livre numérique",
                "autreModele": "",
                "noticeDoc": "http://poc.billib.fr/assets/doc/CountdowntoPoetryWritingStepbyStepApproachtoWritingTechniquesfor7-12Years.pdf",
                "notice": "notice",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 17.80
            },
            {
                "nomArticle": "internet",
                "autreModele": "",
                "notice": "",
                "noticeDoc": "http://poc.billib.fr/assets/doc/TL-PA8030P_KIT_V1_QIG_CA.pdf",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 80.00
            },
            {
                "nomArticle": "Poisson",
                "autreModele": "",
                "notice": "https://www.marmiton.org/recettes/recherche.aspx?aqt=poivron",
                "noticeDoc": "",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 5.00
            },
            {
                "nomArticle": "cereale",
                "autreModele": "",
                "notice": "https://lomi.cafe/articles/tracabilite-cafe",
                "noticeDoc": "",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 12.00
            },
            {
                "nomArticle": "pijama",
                "autreModele": "https://www.youtube.com/watch?v=vNc52MOrVJQ",
                "notice": "",
                "noticeDoc": "",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 70.00
            },
            {
                "nomArticle": "louer",
                "autreModele": "",
                "notice": "",
                "noticeDoc": "http://poc.billib.fr/assets/doc/ct021202.pdf",
                "garantie": "",
                "tuto": "",
                "reparation": "",
                "revente": "",
                "quantite": 10,
                "pu": 2,
                "categories":"",
                "montant": 7.98
            }
        ],
        "net": 171.98,
        "tva": 42.92,
        "total_payer": 214.58
    }